### PR TITLE
Fixes #38

### LINKED ISSUE #38: extend trail attributes to include trail type and interval
as described in picture below. Adding these attributes when including trail with these defaults

img_20170530_144501

### PR DESCRIPTION
**Pull request by dube1503**
Adds additional trail attributes 'type' and 'interval'.

### CODE REVIEW

**Comment by codestar12** [comment]
@dube1503 the shapes mutator looks good. Could you please add interval to be an option to the variable blocks?

**Comment by codestar12** [comment]
@dube1503 also can we change the input on make trail to a drop down with just true or false like the picture in #38

**Comment by dube1503** [comment]
@codestar12 is it a dropdown field or is it a shadow block created with the addition of the make trail attribute?

**Comment by codestar12** [comment]
lets make it a dropdown for now

**Comment by dube1503** [comment]
making it a dropdown "for now" is actually not a very reasonable solution I am coming to discover. All other attributes take inputs and the get_variable block iterates through lists and determines its own type based off the connection of the block in the input space. Therefore, in order to return a type for the value of "make_trail" means rewriting the way the variable blocks work for this only instance, which is possible, but if we want to have a block input for assigning the attribute in the same vain as all the other shape attributes work then it doesnt seem like a good use of time to rewrite this functionality only for us to refactor it back to its original manor if we decide to populate attributes with default shadow blocks as discussed in #57 .
That being said, adding the menu options for the trai_type and interval are necessary regardless.

**Comment by dube1503** [comment]
The newest commit now included the ability to access the new trail features and also updates the block type and color to reflect the type that the block either expect to receive or that it outputs (set and get block respectively).
It also fixes an undiscovered bug that texture had no type assigned to it in the variable block. When testing the typeof a texture assignment in glowscript it returns a type of string so the texture block and variable blocks for textures now reflect this type assignment (uses the string color type).

**Pull request merged**
